{"name": "test_create_tmpfile", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: ''", "trace": "test_convert_yml_to_dict = {'Connection': {'DUT1': {'interfaces': [{'LocalPort': 'Ethernet1', 'RemoteDevice': 'DUT2', 'RemotePort': 'Ethernet11'}...'access': {'ip': '10.1.1.2', 'port': 22, 'protocol': 'ssh'}, 'credentials': {'password': 'onl', 'username': 'admin'}}}}\n\n    def test_create_tmpfile(test_convert_yml_to_dict):\n        temp = test_convert_yml_to_dict\n    \n>       with open(new_filename, 'w+') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: ''\n\ntest_4.py:56: FileNotFoundError"}, "attachments": [{"name": "stdout", "source": "1f8af3d0-dcae-4fa3-ac0c-9fae88895eb4-attachment.txt", "type": "text/plain"}], "start": 1656013333549, "stop": 1656013333550, "uuid": "518febb6-4dbd-4462-9cc6-98eaf333b1d4", "historyId": "047e174eb21cd35aba20cf61d809f7c0", "testCaseId": "4beb7ac807856f851461fca2a912afa6", "fullName": "test_4#test_create_tmpfile", "labels": [{"name": "suite", "value": "test_4"}, {"name": "host", "value": "alexander-Virtual-Machine"}, {"name": "thread", "value": "7561-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_4"}]}